### ISSUE TITLE
Add support for `time` data type

### ISSUE THREAD

**Issue by Vinnl** [inrupt/solid-client-js#1077]
### Search terms you've used
time, data type, addTime, getTime, setTime, removeTime

### Feature suggestion

There currently are `datetime` functions in solid-client, but none to specify a time without a date.

### Expected functionality/enhancement

Functions `getTime`, `addTime`, `setTime` and `removeTime` that are like their `datetime` equivalents, but disregard the date, and store the value as an `xsd:time`.

### Actual functionality/enhancement

Currently you're forced to create a `datetime` with an arbitrary date.

### Use Cases

Some times there's no date that would be relevant - e.g. when storing when school typically closes.

### Additional information

To implement this:

- Add `xsd:time` to the `schemaTypes` we support [in `datatypes.ts`](https://github.com/inrupt/solid-client-js/blob/2ea2ab5b447bae24e5913b32520f6c960bdbac62/src/datatypes.ts#L34).
- Add `serializeTime` and `deserializeTime` to `datatypes.ts` in a way similar to [its datetime equivalents](https://github.com/inrupt/solid-client-js/blob/2ea2ab5b447bae24e5913b32520f6c960bdbac62/src/datatypes.ts#L69-L154), based on the spec that determines [what the stringified format of an `xsd:time` looks like](https://www.w3.org/TR/xmlschema-2/#time-lexical-representation).
- Add the relevant functions to `src/thing/get.ts`, `add.ts`, `set.ts` and `remove.ts` similar to the datetime equivalents.
- Don't forget to update the tests as well :)

Also see #1076 for a similar issue that you can pick up after this.

**Comment by InruptSupport** [comment]
We are currently working on this. Stay tuned.

Inrupt Support
