### ISSUE TITLE
Use @inrupt/lit-generated-vocab-solid-common

### ISSUE THREAD

**Issue by Vinnl** [inrupt/solid-client-js#114]
In `constants.ts` we have a number of IRI's of specific namespaces. The package `@inrupt/lit-generated-vocab-solid-common` has now been published to npm and includes those same constants, so let's use those instead and verify how much that impacts bundle sizes.

**Comment by ThisIsMissEm** [comment]
I think this maybe would me more complicated, as we'd want to move the Artifact Generator to be an officially supported piece of code — currently the SDK team doesn't regularly maintain it, and as @inrupt/lit-generated-vocab-solid-common is built with Artifact Generator, that'd be a blocker

**Comment by ThisIsMissEm** [comment]
We're going to close this as "won't fix" for now, but we have this issue on our backlog to look at later. Artifact Generator is officially supported, but we have a lot of work in our backlog relating to it.
