### ISSUE TITLE
 weird error message on non-existing acl file

### ISSUE THREAD

**Issue by KakoozaJerry** [inrupt/solid-client-js#1157]
I tried to use the library to access the acl for the public and private folders of my personal pod ,

When I try to access `https://pod.inrupt.com/jerrykakooza/public/.acl` > returns 404 not found
But on the private folder `https://pod.inrupt.com/jerrykakooza/private/.acl` returns a 401 of unauthorized

**Comment by NSeydoux** [comment]
Thanks for reaching out ! You may have noticed in the ticket template that we ask some additional elements to be able to help you, namely steps to reproduce the bug you are experiencing, the version of the library you are using, the environment you're working in (e.g. browser or NodeJS)... Would you be able to provide this information ? It would be helpful if you described exactly the steps you've taken and the output you expected, and also to attach the result of `npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers` to the ticket.

There are a couple of elements in the bug you are facing that are of interest: 
- When you get the `401 unauthorized` error, are you issuing an authenticated request ? Some examples are provided in [our documentation](https://docs.inrupt.com/developer-tools/javascript/client-libraries/authentication/) that you may find helpful.
- The title of you ticket mentions ACLs, which is not the access control system implemented by `https://pod.inrupt.com`. Do you specifically want to work with ACLs, or would another access control system be suitable for you ? Additional information is also available in [our documentation](https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/manage-access/).

**Comment by KakoozaJerry** [comment]
So it is just ideal that the result when there is no ACL on a certain resourse most especially the public folder which is a created by default on the inrupt solid pod should return something which is not an error as people will try to search for this ACL

```
$ npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers
```

```


  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
    Memory: 2.26 GB / 3.78 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
  npmPackages:
    @inrupt/solid-client: ^1.6.1 => 1.6.1
    @inrupt/solid-client-authn-browser: ^1.8.1 => 1.8.1
    @inrupt/vocab-common-rdf: ^0.7.4 => 0.7.4
    parcel-bundler: ^1.12.5 => 1.12.5
  npmGlobalPackages:
    npm: 6.14.11
```

**Comment by Vinnl** [comment]
Hi @KakoozaJerry, could you maybe share why you believe that `https://pod.inrupt.com/jerrykakooza/public/.acl` and `https://pod.inrupt.com/jerrykakooza/private/.acl` should exist? The server at pod.inrupt.com will not create those for you.

Note that different Solid servers implement different access control systems - some implement [Web Access Control](https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/manage-access-control-list/) (which works with Access Control Lists), and others, and particularly pod.inrupt.com, implement [Access Control Policies](https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/manage-acp/). solid-client does offer an API that can apply a limited number of access restrictions and transparently does the right thing depending on what the user's server supports in [its universal access control API's](https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/manage-access/), so maybe those are something for you to consider?
