### ISSUE TITLE
Skypack Package Error "@rdfjs/data-model" no dependency version info found.

### ISSUE THREAD

**Issue by Potherca** [inrupt/solid-client-js#1247]
### Search terms you've used

- Skypack
- rdfjs/data-model

### Bug description

When loading this package through Skypack, a Package Error occurs: `"@rdfjs/data-model" no dependency version info found.`

### To Reproduce

1. Load `@inrupt/solid-client` as module from Skypack
    ```html
    <script type="module">
      import solidClient from 'https://cdn.skypack.dev/@inrupt/solid-client';
      /* ... */
    ```
2. See error happen that `@rdf/data-model` is missing version info 
    ![image](https://user-images.githubusercontent.com/195757/132829530-fe63179b-5a6b-4b1b-a59e-c745cb00ed78.png)

https://jsfiddle.net/potherca/63newqf4/4/

### Expected result

No error should occur. Loading through Skypack should just work.

### Actual result

```js
/*
 * [Package Error] "@rdfjs/data-model" no dependency version info found. (Imported by "@inrupt/solid-client").
 *
 * The package "@inrupt/solid-client" depends on "@rdfjs/data-model" as a dependency,
 * but did not list any dependency version info in its package manifest.
 * Without this information, the CDN is unable to properly resolve this import.
 *
 * How to fix:
 *   - Let the "@inrupt/solid-client" package author know that "@rdfjs/data-model" needs to be included in their package.json manifest.
 *   - Use https://skypack.dev/ to find a web-friendly alternative to find another package.
 */

throw new Error("[Package Error] \"@rdfjs/data-model\" no dependency version info found. (Imported by \"@inrupt/solid-client\").");
export default null;
```

### Environment

Online. Any browser.

## Additional information

_None yet_

**Comment by Potherca** [comment]
As I am not sure if this should be added as external export in `rollup.config.js` and my NPM updates the package manifest to lockfileVersion 2, I have not created an MR to fix this.

To demonstrate things _do_ work when the version constraint is added, I have created a fork which adds `"@rdfjs/data-model": "^1.3.3",` to the `package.json` and (temporarily) published this as [@potherca/inrupt-solid-client](https://www.npmjs.com/package/@potherca/inrupt-solid-client).

This can be seen to work by using `https://cdn.skypack.dev/@potherca/inrupt-solid-client` as import URI.

**Comment by Potherca** [comment]
Possibly related, my next problem is `Uncaught (in promise) TypeError: n3 is null`.

I am hesitant to open a new issue, since this maybe be part of the same issue. Or maybe something to do with [rollup.config.js](https://github.com/inrupt/solid-client-js/blob/613861189da0c5ec5e86e5836807b81028ae1384/rollup.config.js#L64)?

Not sure :disappointed:

**Comment by ThisIsMissEm** [comment]
This error is expected, as loading via CDN as UMD (or similar) requires that you also have loaded the external dependencies: https://github.com/inrupt/solid-client-js/blob/main/rollup.config.js#L62-L68

We don't bundle the dependencies as part of what we ship.
