### ISSUE TITLE
missing XmlSchemaTypeIri in built types

### ISSUE THREAD

**Issue by pduchesne** [inrupt/solid-client-js#1275]
### Bug description
The published `.d.ts` files do not transpile when imported in a TS project.
The culprit is the `rdf.internal.d.ts` that exposes the `XmlSchemaTypeIri` type, which is itself marked as @internal and therefore excluded from the built types.

### To Reproduce
The simplest TS project will do (as https://codesandbox.io/s/missing-xmlschematypeiri-s0rv4), and will fail when running `tsc` with 
```
 error TS2305: Module '"./datatypes"' has no exported member 'XmlSchemaTypeIri'.
``` 
(it will not fail within codesandbox though)

**Comment by Maximvdw** [comment]
While not a solution, a temporary fix could be to add a ```skipLibCheck: true``` in your tsconfig compiler options

**Comment by ThisIsMissEm** [comment]
Fixed in https://github.com/inrupt/solid-client-js/pull/1303

**Comment by nicolasmondada** [comment]
Hi there,
We don't use that @internal decorator any more. This is fixed.
