### ISSUE TITLE
403 Forbidden unexpected

### ISSUE THREAD

**Issue by vincenzo-dip8** [inrupt/solid-client-js#1329]
Hi everyone,

I've encountered an error trying to get the permission linked to a resource after its updating on a Pod.
This is the scenario:

- I ve initialized a Pod creating some folders and assigning **full** access to them to an user1 (and also explicit for the admin - just to stay safe).
- I ve initialized those folders/Container by uploading some file and assigning **full** access to them to the user1 (and also explicit for the admin - just to stay secure).
- i ve checked that the permission was assigned correctly. **NOTE**: to check i ve used the logged session of the admin of POD.

Till now all work fine.

Then, i made some operations such as retrieve some of these file, and still all work fine. **NOTE**: those operations was made by logged session of the user1, so the access previously assigned to him work fine.

Now, what i m trying to do is to add as "user1" other files  (so using the FULL access policies set above), **but** different (file) from those updated as admin during the initialization of the scenario (in the sense that those new file should not have previously setted access or other). 
The upload work fine, but if I try to set the access for these new file as user1 (which have FULL access to do this), this return me:
```
FetchError: Fetching the metadata of the Resource at [https://pod.inrupt.com/***********/Or
der-i1ir2osnb.json] failed: [403] [Forbidden].
```
Furthermore, This error appen also when i want to check the permission or if i want to delete this file, still using user1 logged session.

So, i ve tried to check manually, as admin, the access for these file (previously uploaded as user1) for the user1 webID, and return me an All-False access. **How this could be possible considering that the file were uploaded by the user with full-access?**

**RECAP**: Seems that i have to insert file i need as admin, set the access for the users i want, and then users can operate through these access. But this solution is not welcome.

**Comment by AyazDyshin** [comment]
if this is indeed the format of url that you have used: https://pod.inrupt.com/***********/Order-i1ir2osnb.json the problem might be in the missing slash in the end (/).

**Comment by ThisIsMissEm** [comment]
As of July 2022, the server that is PodSpaces has been completely rewritten with a new version (ESS 2.0 is a complete rewrite from ESS 1.x), so this may not be an issue still.

Without code showing what you're doing, I can't offer any assistance here. 403 Forbidden tends to be that you're trying to access a resource without correct authentication / authorization.

Feel free to reopen if this is still an issue for you. Please note: `pod.inrupt.com` doesn't exist anymore, as it's now `id.inrupt.com` for WebIDs and `storage.inrupt.com` for the pod
