### ISSUE TITLE
URNs are not supported

### ISSUE THREAD

**Issue by ianconsolata** [inrupt/solid-client-js#1347]
### Search terms you've used
createThing, URN, urn

### Bug description / Feature suggestion
URNs are valid URIs / IRIs for RDF: https://afs.github.io/rdf-iri-syntax.html, and are especially useful as location independent identifiers for RDF subjects. However, the Inrupt client library currently only support createThing(url) and createThing(name) neither of which allow you to set a URN.

### Expected functionality/enhancement

Creates a Thing with the subject set to the given URN

### Actual functionality/enhancement

createThingOptions does not currently accept a `urn` parameter. Setting a URN to the url parameter, i.e. createThing(url: `urn:uuid:3070f274-4975-11ec-81d3-0242ac130003`), throws an error because URNs are not URLs.

### Use Cases
Among other things it would allow us to start using any well known URN scheme (like `urn:isbn`) to add metadata and annotations to location independent identifiers.

createThing() could return a random `urn:uuid` rather than just a random fragment prefixed by the resource, divorcing the identity of the created thing from the dataset it was first written to. URN indexed things can also be easily moved between datasets without needing to modify or update any associated links.

**Comment by ianconsolata** [comment]
Ooops, never mind! I saw that everything shells out to https://github.com/inrupt/solid-client-js/blob/125fcfac5e9e21a1a1e55ad0fa507d594c515121/src/datatypes.ts#L501, and it looks like `new Url('urn:uuid:3070f274-4975-11ec-81d3-0242ac130003')` doesn't actually throw when you give it a URN, so this should already work.

**Comment by ThisIsMissEm** [comment]
@ianconsolata is this now working for you and we can close this issue?
