### ISSUE TITLE
E2E node test runs are not isolated

### ISSUE THREAD

**Issue by edwardsph** [inrupt/solid-client-js#1598]
### Search terms you've used
test isolation

### Bug description
Test runs are not isolated from each other so test running concurrently on the same Pod will fail, as will test running in a Pod that has leftover artefacts from a previous test.

### To Reproduce

1. Run the tests and stop them before they tear down happens
2. Run the tests again and they will fail

### Expected result
Test pass every time they are run

## Additional information
I suggest any test artefacts are created with UUIDs (or short unique names) so that each test run is isolated from others. This will make them less prone to false failures.

Examples of problematic artefacts:
* solid-client-tests/
* solid-client-test-e2e-acp/

**Comment by ThisIsMissEm** [comment]
This is only when running locally, and is intended. If you set the `CI` env variable, then the containers will be given unique names and the tests be able to run concurrently.

In development, we don't randomise names or run concurrently as to allow us to debug failing tests.

**Comment by ThisIsMissEm** [comment]
We could perhaps add a "beforeAll" that removes existing resources if CI isn't set.
