### ISSUE TITLE
Where are the JavaScript files

### ISSUE THREAD

**Issue by sbuchok** [inrupt/solid-client-js#1772]
I do not want to have to use NPM. 
I do not want to have to use TypeScript. 
This is supposed to be a JavaScript library, yet I see no JavaScript files anywhere. 

The current frontend ecosystem is a little ridiculous. I need to have Webpack (or whatever it was replaced with) so that I can use NPM so that I can get TypeScript so that I can transpile the TypeScript to JavaScript... Why do people just not provide the JavaScript files?

Why the toolchain for something that literally should just require the use of the script tag to a file?

This is coming across bitchy, I know, sorry, it's just I want to start looking at this and having fun, but I don't want any of the aforementioned dependencies above.

Can there not be an install that doesn't require npm?
https://docs.inrupt.com/developer-tools/javascript/client-libraries/

**Comment by Vinnl** [comment]
@sbuchok You're just looking at the source code, but the JS is generated from it and is available in various places. For example, there's unpkg.com: https://unpkg.com/@inrupt/solid-client

**Comment by sbuchok** [comment]
@Vinnl That looks perfect, thank you. Again, sorry about the bitchiness. It would be nice if this info was put directly on the inrupt website.

Thanks again.
