### ISSUE TITLE
Create a working version that is just JavaScript

### ISSUE THREAD

**Issue by sbuchok** [inrupt/solid-client-js#1774]
I used unpkg.com to get the JS versions of the various files. The problem is that there are dependencies on using require in solid-client-authn-browser.
It also uses require("@inrupt/solid-client-authn-core"); which I'm guess would mean that I would need to change that to an import and use unpkg.com on that as well, not to mention "require("./Session");" and others like it.
I'm trying to get this working without NPM or TypeScript as dependencies, however, without using specific build tools I can't seem to get it working. Since this is supposed to be a JavaScript library, can you include a working version that is ONLY JavaScript, no other dependencies?

**Comment by NSeydoux** [comment]
Hello @sbuchok, thanks for reaching out. I'm not sure I understand your question: Typescript is something that impacts development, but once transpiled, the result is plain JS, so things should be transparent to any JavaScript codebase that doesn't want to opt-in TypeScript. So if you are using JavaScript, and you add a dependency on `@inrupt/solid-client`, you're not getting any TS annotations in. Similarily, `@inrupt/solid-client-authn-core` is a dev dependency of `solid-client`, not a production dependency, so it should not impact you as a consumer of the library unless you want to make contributions to the library directly.

NPM is the recommanded way to depend on our libraries, but I guess if you want to add a dependency to an ESM from a `script` tag, you should be able to use something like https://unpkg.com/browse/@inrupt/solid-client@1.23.3/dist/index.mjs. I'm not very familiar with unpkg though, so I may be off-topic.

**Comment by sbuchok** [comment]
Basically, I want to use solid without the dependency of NPM. How would I go about doing this? It's supposed to be a JavaScript library, so I should just be able to import or use a script tag, however, as it stands, you can only use this if you have NPM and transpile from TypeScript to JavaScript. 

I was hoping I could just run it through unpkg, however, that doesn't seem to work. How do I get ahold of just the JS files, no NPM, no TypeScript, no fuss?
Is there a CDN that can point to the JS files somewhere?

**Comment by ThisIsMissEm** [comment]
@sbuchok currently that's not something we develop for, as most projects are using npm and some sort of build system (parcel, webpack, vite, etc), but you may have luck with the UMD output, instead of the ESM output: https://unpkg.com/browse/@inrupt/solid-client@1.23.3/umd/index.js

Just keep in mind that you'll need to load both solid-client and solid-client-authn-browser, as there's a dependency between the two

**Comment by sbuchok** [comment]
I don't understand. You are putting out a JavaScript library. Where are the JavaScript files? Why can I not use import or a script tag? Why do I have to use NPM? **"as most projects are using NPM and some sort of build system"** And most projects now have unneeded dependencies. Do you want Solid to be used in the most number of scenarios? Then allow for the case that provides the widest net. You are purposely perpetuating the need for people to have to use NPM and other build tools that aren't needed. Sure, you want to build a big monolithic system, great, these tools can help. You want to build a small site, then these tools are a hindrance.
Please provide the actual JS files for people to use or put them in a CDN. I don't understand why you guys are against making this as simple as possible for everyone who wants to use the library.

**Comment by ThisIsMissEm** [comment]
We don't operate a CDN for serving javascript files. The two links provided above for unpkg.com might work, though we can't guarantee as we do not operate unpkg; there's also jsdelivr.com, CDNJS, cdnpkg, etc, etc.

The compiled output of our SDKs is just JavaScript — modern JavaScript. You might want to look at using ESM, and then using JavaScript Modules for script tags: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

JavaScript has changed a lot in the past 10 years.

**Comment by sbuchok** [comment]
**"The compiled output of our SDKs is just JavaScript — modern JavaScript"** - so why don't you put links to these "compiled" files? I can use NPM, I know how. I know how modules work, but you are requiring people to use NPM. Why? "Oh, it's the modern way to blah blah blah", come on. What you guys don't seem to understand is that not everyone wants to use these build tools. Not everyone wants to use NPM or node or TypeScript or ... There is a large number of people who use Vanilla JS with as few dependencies as possible. I was extremely excited to look into using Solid and created a Pod last night. I think this is absolutely the way to go for the future. 

I guess I will create a separate project now so that I can get the plain JS files, but why on earth don't you guys supply them? Stop thinking that everyone wants to use this "modern" way of these build chains. Just supply the compiled output (which is funny to say cause it's not a binary, it's JavaScript).
