### ISSUE TITLE
AccessModes not exported from universalAccess module or main solid-client module

### ISSUE THREAD

**Issue by ianconsolata** [inrupt/solid-client-js#1862]
### Search terms you've used

AccessModes

### Bug description

The AccessModes type is not exported from the `universalAccess` module. This means when using TypeScript, there is no clear way to get the associated types while using that module.

### Expected result

I can import the AccessModes type.

### Actual result

I cannot import the AccessModes type from either the universalAccess module or the main solid-client module.

**Comment by NSeydoux** [comment]
Hi @ianconsolata, thanks for reporting this! We'll patch this soon, and I'll update this issue accordingly.

**Comment by NSeydoux** [comment]
https://github.com/inrupt/solid-client-js/releases/tag/v1.26.0 should resolve this. Thanks again for reporting.

**Comment by jeswr** [comment]
Closing as completed - @ianconsolata feel free to re-open the issue if problems persist.
