### ISSUE TITLE
Policy under unnamed node is not returned from `getResourcePolicyAll()`

### ISSUE THREAD

**Issue by renyuneyun** [inrupt/solid-client-js#2339]
### Search terms you've used

- ACP
- getResourcePolicyAll
- getPolicyUrlAll

### Bug description

When following [the document](https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/manage-acp/#view-policies-and-matchers-for-a-resource) to get policies, it seems only policies with named nodes are returned from `acp_ess_2.getResourcePolicyAll()`. This looks like a bug rather than intentional choice, as apparently `.acr` documents can contain unnamed `acp:Policy` nodes.

### To Reproduce

1. Create a `.acr` with unnamed policy nodes
2. Call `acp_ess_2.getResourcePolicyAll()` for that resource

**Minimal reproduction**

Example `.acr` file: https://gist.github.com/renyuneyun/834eb5ee542e06a2cc3ee1a57712ca3f

### Expected result

All `acp:Policy` nodes are returned in some form.

### Actual result

Only named nodes (of `acp:Policy`) are returned.

### Environment

```
  System:
    OS: Linux 6.6 Arch Linux
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 1.90 GB / 15.40 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.1 - ~/node_modules/.bin/node
    Yarn: 1.22.21 - /usr/bin/yarn
    npm: 10.4.0 - /usr/bin/npm
  Browsers:
    Chromium: 122.0.6261.57
  npmPackages:
    @comunica/query-sparql: ^2.8.1 => 2.10.0 
    @inrupt/solid-client: ^2.0.0 => 2.0.0 
    @inrupt/solid-client-authn-browser: ^2.0.0 => 2.0.0 
    @inrupt/vocab-common-rdf: ^1.0.5 => 1.0.5 
    @inrupt/vocab-solid: ^1.0.4 => 1.0.4 
    @mdi/font: ^7.1.96 => 7.2.96 
    @renyuneyun/solid-helper: ^0.0.3 => 0.0.3 
    @rushstack/eslint-patch: ^1.1.4 => 1.3.2 
    @tsconfig/node20: ^20.1.0 => 20.1.0 
    @types/n3: ^1.10.4 => 1.16.0 
    @types/node: ^20.4.4 => 20.4.4 
    @vitejs/plugin-vue: ^4.0.0 => 4.2.3 
    @vue/eslint-config-prettier: ^8.0.0 => 8.0.0 
    @vue/eslint-config-typescript: ^11.0.0 => 11.0.3 
    @vue/tsconfig: ^0.4.0 => 0.4.0 
    eslint: ^8.22.0 => 8.45.0 
    eslint-plugin-vue: ^9.3.0 => 9.15.1 
    n3: ^1.16.3 => 1.17.2 
    npm-run-all: ^4.1.5 => 4.1.5 
    path-browserify: ^1.0.1 => 1.0.1 
    pinia: ^2.1.4 => 2.1.4 
    prettier: ^3.0.0 => 3.0.0 
    solid-helper-vue: ^0.1.4 => 0.1.4 
    typescript: ^5.1.6 => 5.1.6 
    vite: ^4.0.0 => 4.4.6 
    vue: ^3.3.4 => 3.3.4 
    vue-tsc: ^1.0.12 => 1.8.6 
    vuetify: ^3.3.9 => 3.3.9 
  npmGlobalPackages:
    @quasar/cli: 2.3.0
    @renyuneyun/solid-helper: 0.0.3
    @renyuneyun/parse-link-header-ts: 1.0.1
    orchestrator-app: 0.1.0
    solid-helper-vue: 0.2.0
    solid-shell: 2.0.8
    vercel: 32.5.5
```

## Additional information

I guess it's hard to implement this for `getPolicyUrlAll()`, as unnamed nodes don't have URLs. But it should be possible for `getResourcePolicyAll()`, which returns a dataset representing the node).

**Comment by NSeydoux** [comment]
Hi @renyuneyun ,
This looks like a bug indeed, from a conflict between our implementation of a `Dataset` filtering out blank nodes and the fact that nothing prevents policies from being Blank Nodes. 

I'll look into how this can be sorted out.
