### ISSUE TITLE
Add timestamp to notifications

### ISSUE THREAD

**Issue by NSeydoux** [inrupt/solid-client-js#252]
**Search terms you've used**

Notification, Timestamp

**Is your feature request related to a problem? Please describe.**

When building a notification, the provenance information only contains the notification actor, but not the time where the notification was created. This would be an issue when processing notifications as a chronological stream of events.

**Describe the solution you'd like**

Have the library add a notification timestamp when building the notification, without requiring any input from the caller.

**Describe alternatives you've considered**

Have the caller provide the timestamp, or not add a timestamp at all.

**Comment by nicolasmondada** [comment]
This will be addressed when we add proper support for notifications.
