### ISSUE TITLE
Finding Thing(s) given some criteria

### ISSUE THREAD

**Issue by YuukanOO** [inrupt/solid-client-js#353]
Hi there! Hope I'm using the right template for this question 😀

**Search terms you've used**

query, find

**What problem are you trying to solve? Please describe.**

Almost every application needs to find data matching some specific criteria (some object containg a string, an integer range, and so on...) and I would like to know what this library will provide in the future? I don't want to retrieve all `Thing` locally to evaluate some predicate and filter *client side* and I'm thinking about using SPARQL queries to ask the server to do the hard job for us but maybe there's another nifty way.

I'm aware that, as of now, the support for SPARQL in the Solid spec is already being discussed...

**What existing documentation is relevant to your problem, and why is it insufficient?**

https://docs.inrupt.com/client-libraries/solid-client-js/tutorial/read-write-data.html#read-data
https://docs.inrupt.com/client-libraries/solid-client-js/api/modules/_thing_get_.html

**Additional context**

This question arise because I'm building a tiny library depending only on `@inrupt/solid-client` to make the mapping between my javascript objects and triples easier and more pleasant to work with and making easy and efficient to query for data with specific criteria is a must have.

Constructing and making a SPARQL query against a Solid document works like a charm, I can get back some turtle but since the function `turtleToTriples` is marked as internal, I can't use it and need to duplicate it on my side and this is why I'm here to see if there's another take on your side for this problem.

I will make the repo public as soon as my public API is done.

Thanks for reading me and this library BTW 👍

**Comment by Vinnl** [comment]
Hi @YuukanOO, if I understand this correctly, you want the filtering to happen on the server-side, is that correct?

If so, then we are indeed dependent on support for that in the spec (and, of course, the server). Tracking the spec is an explicit goal, so if this were to be added to the spec, we would certainly look at how we can support that.

But until then, I don't think there is anything we can do for you? If there is, let us know :) 

(Also, looking forward to seeing what you are working on!)

**Comment by YuukanOO** [comment]
> Hi @YuukanOO, if I understand this correctly, you want the filtering to happen on the server-side, is that correct?

Exactly 👌 This is the kind of things we always do, whatever the application being developed, when it comes to retrieve data : ask the component who store the data (the server, here the pod) to do the heavy lifting.

Filtering data on the client side is easier but I'm afraid for large datasets performances (but maybe I'm totally biased here since I'm used to traditional databases hosting data for every users).

> If so, then we are indeed dependent on support for that in the spec (and, of course, the server). Tracking the spec is an explicit goal, so if this were to be added to the spec, we would certainly look at how we can support that. Until we have more clarity on that, however, there are no concrete plans we can share.

I totally understand.
 
> Until then, I don't think there is anything we can do for you? If there is, let us know :)

So, the current approach is to retrieve all things locally and filter them here?

> (Also, looking forward to seeing what you are working on!)

I'm on it 😉

Anyway, thanks for the quick answer!

**Comment by Vinnl** [comment]
> So, the current approach is to retrieve all things locally and filter them here?

Yes, I'm afraid there's nothing more we can do as a client - best way to deal with that is to spread the data over multiple Resources if it grows unmanageable, at this point in time.

**Comment by YuukanOO** [comment]
Makes sense! Closing this issue till things evolve on the server side.
