### ISSUE TITLE
getUrl(resource, AS.type)

### ISSUE THREAD

**Issue by scenaristeur** [inrupt/solid-client-js#401]
hi ! 
I absolutely don't understand why a getUrl or getNamedNode throw me an error with https://www.w3.org/ns/activitystreams#type

the doc is build with Tripledoc at https://agora.solid.community/public/popock/inbox/
with https://github.com/scenaristeur/solid-vue-panes/blob/71668f80aa41c26f8cf9171cc0d24f07ab262d12/src/components/agora/Agora.vue#L104
```
  let activityDoc = {}
    try{
      activityDoc = await fetchDocument(fileUrl);
    }catch(e){
      activityDoc = await createDocument(fileUrl);
    }

    console.log("webId",this.webId)
    let autoSummary = [this.activity.actor.name, this.activity.type, "a", this.activity.object.type, "with name", this.activity.object.name].join(" ")
    console.log("Musr create outbox object first, then activity !",activityDoc, messageId, date)
    let subj =   activityDoc.addSubject({identifier:messageId})
    //subj.addLiteral(sioc.content, this.activity)
    subj.addLiteral(rdfs.label, autoSummary)
    subj.addLiteral(dct.created, date)
    subj.addRef(foaf.maker, this.webId)
    subj.addRef('https://www.w3.org/ns/activitystreams#actor', this.webId)
    subj.addRef(rdf.type, 'https://www.w3.org/ns/activitystreams#'+this.activity.type)
    subj.addLiteral('https://www.w3.org/ns/activitystreams#summary', this.activity.summary)
    subj.addRef('https://www.w3.org/ns/activitystreams#type', 'https://www.w3.org/ns/activitystreams#'+this.activity.type)
    subj.addLiteral('https://www.w3.org/ns/activitystreams#object', "test"+this.activity.object)
    await activityDoc.save();

```
then i can retrieve all that data , but not AS.type , with the code : 
https://github.com/scenaristeur/solid-vue-panes/blob/71668f80aa41c26f8cf9171cc0d24f07ab262d12/src/components/agora/ActivityItem.vue#L41
```
  this.label = getStringNoLocale(this.activity, RDFS.label);
      this.created = getStringNoLocale(this.activity, DCTERMS.created);
      this.summary = getStringNoLocale(this.activity, AS.summary);
      this.object = getStringNoLocale(this.activity, AS.object);
      console.log("Summary",this.summary)
      this.maker = getUrl(this.activity, FOAF.maker);
      console.log("maker", this.maker)
      this.actor = getUrl(this.activity, AS.actor);
      console.log("actor",this.actor)
      this.type = getUrl(this.activity, RDF.type);
      console.log("type", this.type)
      /* THE CODE AFTER THROW ERROR
    */
      this.type2 = getUrl(this.activity, AS.type);
      console.log("type AS", this.type2)
```
![image](https://user-images.githubusercontent.com/4020744/91736785-810a6380-ebae-11ea-9e0d-dfa038cfbce8.png)

the online demo is https://scenaristeur.github.io/solid-vue-panes/agora

If i do something wrong, I absolutely does not know what

**Comment by Vinnl** [comment]
Hi @scenaristeur, the problem here is that ActivityStreams does not actually define `https://www.w3.org/ns/activitystreams#type`, and hence `@inrupt/vocab-common-rdf` does not include it. Thus, if you inspect `AS.type`, you'll see that it is `undefined`. Could it be that it should actually be `http://www.w3.org/1999/02/22-rdf-syntax-ns#type`?

**Comment by scenaristeur** [comment]
Oh sorry, I thought https://www.w3.org/TR/activitystreams-vocabulary/#dfn-type was an as.type. and wanted to be as conform to vocab as possible, but I could effectively stay with rdf.type. 
10 0000 thxs

**Comment by Vinnl** [comment]
@scenaristeur Hmm, that is weird. I'm not too familiar with AS, but that does look like it should be supported as far as I can see. In that case, you might want to report the fact that `@inrupt/vocab-common-rdf` does not export it over here: https://github.com/inrupt/solid-common-vocab-rdf/issues

**Comment by scenaristeur** [comment]
Well not defined nor in https://www.w3.org/ns/activitystreams-owl . It seems it is a JSON-LD definition https://json-ld.org/spec/latest/json-ld/#dfn-type-maps

**Comment by NSeydoux** [comment]
You are right @scenaristeur: `@type` is a JSON-LD keyword, that is broader than `rdf:type`, since it both applies to typed nodes (similar to `rdf:type`) but also to typed values (e.g. `xsd:integer`). The way it is introduced in https://www.w3.org/TR/activitystreams-vocabulary/#dfn-type is a bit surprising, because it looks like it is part of the AS vocabulary, but it should not be. It looks like in your use case, you should be fine with `rdf:type` though.
