### ISSUE TITLE
Test bug

### ISSUE THREAD

**Issue by nicolasmondada** [inrupt/solid-client-js#533]
**Search terms you've used**

This is a test bug

**Describe the bug**

**To Reproduce**

1. Given this data: `…`
2. Call this function `…`
3. See error

**CodeSandbox**

**Expected behavior**

**Log output**

**Environment**

```
$ npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers


```

**Additional context**

**Comment by nicolasmondada** [comment]
test comment

**Comment by Vinnl** [comment]
@nicolasmondada Did the test succeed? Can we close this bug?
