### ISSUE TITLE
in "Getting Started: Part 1", in step 5 "Run the Application" we get a regex error

### ISSUE THREAD

**Issue by mjstroh** [inrupt/solid-client-js#607]
### Search terms you've used

Pasted the error into DucDuckGo search engine

### Bug description

Regex error: 
SyntaxError: Invalid regular expression: /(\p{Uppercase_Letter}+|\p{Lowercase_Letter}|\d)(\p{Uppercase_Letter}+)/: Invalid escape

### To Reproduce
1. Go to Documentation: Introduction: "Getting Started: Part 1"
2. Complete all steps to Step 5
3. In Step 5. Run the Application, we get the error

**Minimal reproduction**

### Expected result

execute "npm run build && npm run start"

Result should be

ℹ ｢wds｣: Project is running at http://localhost:8080/
...
ℹ ｢wdm｣: Compiled successfully.

### Actual result

```
$ npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers
```
 System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 113.56 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 8.9.1 - /usr/local/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.198
    Firefox: 77.0.1
    Safari: 14.0
  npmPackages:
    @inrupt/solid-client: ^1.0.0 => 1.0.0 
    @inrupt/solid-client-authn-browser: ^1.0.0 => 1.0.0 
    @inrupt/vocab-common-rdf: ^0.6.3 => 0.6.3 
    css-loader: ^5.0.1 => 5.0.1 
    style-loader: ^2.0.0 => 2.0.0 
    webpack: ^5.4.0 => 5.4.0 
    webpack-cli: ^4.2.0 => 4.2.0 
    webpack-dev-server: ^3.11.0 => 3.11.0 
  npmGlobalPackages:
    @angular/cli: 1.6.2
    composer-playground: 0.20.7
    generator-blockstack: 0.1.9
    npm: 6.14.8
    remix-ide: 0.6.4
    yo: 2.0.0

**Comment by mjstroh** [comment]
Error is 
> my-demo-app@1.0.0 build /Users/XXXX/solid/my-demo-app
> webpack

/Users/XXXX/solid/my-demo-app/node_modules/webpack/lib/cli.js:66
			.replace(
			^

SyntaxError: Invalid regular expression: /(\p{Uppercase_Letter}+|\p{Lowercase_Letter}|\d)(\p{Uppercase_Letter}+)/: Invalid escape
    at pathToArgumentName (/Users/XXXX/solid/my-demo-app/node_modules/webpack/lib/cli.js:66:4)
    at addFlag (/Users/XXXX/solid/my-demo-app/node_modules/webpack/lib/cli.js:170:16)
    at traverse (/Users/XXXX/solid/my-demo-app/node_modules/webpack/lib/cli.js:243:21)
    at traverse (/Users/XXXX/solid/my-demo-app/node_modules/webpack/lib/cli.js:299:23)
    at traverse (/Users/XXXX/solid/my-demo-app/node_modules/webpack/lib/cli.js:248:24)
    at Object.getArguments (/Users/XXXX/solid/my-demo-app/node_modules/webpack/lib/cli.js:308:2)
    at Object.<anonymous> (/Users/XXXX/solid/my-demo-app/node_modules/webpack-cli/lib/utils/cli-flags.js:245:30)
    at Module._compile (/Users/XXXX/solid/my-demo-app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-demo-app@1.0.0 build: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-demo-app@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by kevin-inrupt** [comment]
Hi Michael,

Thank you for contacting Inrupt Support. Reviewing the information you provided, this could be a duplicate of https://github.com/inrupt/solid-client-authn-js/issues/551 that was addressed end of last week. I will check with the team to see if this has been included in the latest version of the client libraries released to npm.

Best,

Kevin

**Comment by kevin-inrupt** [comment]
Hi Michael,

Investigating further, I could not replicate the issue you described on macOS 11.0.1 / 16 Gb RAM / i5 CPU. The application built and executed successfully:

> % npm run build && npm run start                                                       
> 
> > my-demo-app@1.0.0 build /Users/XXXXXX/my-demo-app
> > webpack
> 
> [webpack-cli] Compilation finished
> asset index.js 5.05 MiB [emitted] (name: main)
> runtime modules 1.25 KiB 6 modules
> orphan modules 33.8 KiB [orphan] 4 modules
> javascript modules 4.2 MiB
>   modules by path ./node_modules/ 4.2 MiB 624 modules
>   ./src/index.js 2.73 KiB [built] [code generated]
>   util (ignored) 15 bytes [built] [code generated]
>   crypto (ignored) 15 bytes [built] [code generated]
>   buffer (ignored) 15 bytes [optional] [built] [code generated]
> json modules 16.7 KiB
>   modules by path ./node_modules/ajv/lib/refs/*.json 3.12 KiB 2 modules
>   modules by path ./node_modules/browserify-sign/browser/*.json 2.23 KiB
>     ./node_modules/browserify-sign/browser/algorithms.json 2.07 KiB [built] [code generated]
>     ./node_modules/browserify-sign/browser/curves.json 162 bytes [built] [code generated]
> webpack 5.4.0 compiled successfully in 2866 ms
> 
> > my-demo-app@1.0.0 start /Users/XXXXXX/my-demo-app
> > webpack serve --open true
> 
> ℹ ｢wds｣: Project is running at http://localhost:8080/
> ℹ ｢wds｣: webpack output is served from undefined
> ℹ ｢wds｣: Content not from webpack is served from ./dist
> ℹ ｢wdm｣: asset index.js 5.38 MiB [emitted] (name: main)
> runtime modules 1.25 KiB 6 modules
> orphan modules 33.8 KiB [orphan] 4 modules
> javascript modules 4.51 MiB
>   modules by path ./node_modules/ 4.51 MiB 649 modules
>   ./src/index.js 2.73 KiB [built] [code generated]
>   util (ignored) 15 bytes [built] [code generated]
>   crypto (ignored) 15 bytes [built] [code generated]
>   buffer (ignored) 15 bytes [optional] [built] [code generated]
> json modules 16.7 KiB
>   modules by path ./node_modules/ajv/lib/refs/*.json 3.12 KiB 2 modules
>   modules by path ./node_modules/browserify-sign/browser/*.json 2.23 KiB
>     ./node_modules/browserify-sign/browser/algorithms.json 2.07 KiB [built] [code generated]
>     ./node_modules/browserify-sign/browser/curves.json 162 bytes [built] [code generated]
> webpack 5.4.0 compiled successfully in 2898 ms
> ℹ ｢wdm｣: Compiled successfully.

Was there anything else with you configuration or files that differed from documentation?

Kevin

**Comment by kevin-inrupt** [comment]
As a quick follow-up, one of our developers noticed that the specific line of code in Webpack that triggered the error was changed in a commit that was release 13 days ago: https://github.com/webpack/webpack/commit/483d935560ae942ee455406f26c1a1375ed9f3e0.

Kevin

**Comment by mjstroh** [comment]
I would expect this code to run without error on a range of devices. You can see the config as listed above. This is a legitimate error - a regex error. Can I ask you to investigate further?

**Comment by kevin-inrupt** [comment]
Hi Michael.,

The code certainly should run successfully on a range of devices. We develop and test the code on Ubuntu and macOS - unfortunately we are struggling to replicate the Regex error you are seeing. 

Comparing your machines configuration against my macOS laptop, most things are the same/similar other than the relatively old version of Node you have installed,v8.9.1, vs v12.18.3 on my laptop. There are reports of issues similar to the one you are seeing (https://github.com/DivanteLtd/vue-storefront-api/issues/338) when using older versions of Node. Is it possible for you to upgrade Node and retry?

Kevin

**Comment by Vinnl** [comment]
@kevin-inrupt Well-spotted: I can reproduce the issue when using Node 8 on Ubuntu. Version 10 [is the minimum version supported by Webpack](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#minimum-nodejs-version), and Node 8 itself has reached end-of-life. We'll call that out explicitly in the docs.

@mjstroh Could you confirm whether using a more recent version of Node resolves the issue for you? As a general tip, you can use [nvm](https://github.com/nvm-sh/nvm) to manage multiple versions of Node on the same system, in case you still need v8 for other projects.

**Comment by mjstroh** [comment]
Please note that when I installed the latest version of node.js via brew, the program compiled successfully.

**Comment by mjstroh** [comment]
All good now!

**Comment by Vinnl** [comment]
Great, thanks for reporting back! (And for helping future readers of the docs for whom this will be explicitly pointed out.)

**Comment by jhgoebbert** [comment]
Just for everyone who comes along this issue:
`Invalid regular expression: /(\p{Uppercase_Letter}+|\p{Lowercase_Letter}|\d)(\p{Uppercase_Letter}+)/:` is very likely related to a NodeJS which was build with `--with-intl=none` and does not include [RegExp Unicode Property Escapes](https://github.com/tc39/proposal-regexp-unicode-property-escapes)
