### ISSUE TITLE
solid.getPermissions for ds.internal_resourceInfo.permissions

### ISSUE THREAD

**Issue by gibsonf1** [inrupt/solid-client-js#765]
It would be nice to not have to use internal api to getPermissions on a datasource

**Comment by nicolasmondada** [comment]
Hi @gibsonf1 ,

Thanks for submitting this feature request. Indeed this is something that we have in our backlog and we are looking at when we could slot this in. We'll keep this issue updated as we have more information.

Cheers,
Nick

**Comment by Vinnl** [comment]
I just released solid-client 1.7.0, which adds a new `getEffectiveAccess()` function. That should allow you to get the values of the `WAC-Allow` header for servers that implement WAC. (It also gives you user access for servers that implement ACPs, but unfortunately that proposal doesn't currently expose information for unauthenticated users.)

Feel free to file new Issues in GitHub if you have further requests :)
