### ISSUE TITLE
client.getTypes instead of  ds.internal_resourceInfo.linkedResources.type

### ISSUE THREAD

**Issue by gibsonf1** [inrupt/solid-client-js#766]
Would be nice to have a function like client.getTypes to get the types of a datasource instead of using internal api

**Comment by nicolasmondada** [comment]
Hi @gibsonf1 ,

Is this about checking if a resource is a RDF or non-RDF resource? Is `isRawData` the answer to your request?

Cheers,
Nick.-

**Comment by gibsonf1** [comment]
@nicolasmondada   This one is about getting the rdf:type s that a resource is through the link header

**Comment by Vinnl** [comment]
I just released solid-client 1.7.0, which adds a new `getLinkedResourceUrlAll()` function, which gives you access to the Link headers of a Resource. Keep in mind that not every header is mandated by the Solid spec, so a Solid app cannot assume every header to always be present.

Feel free to file new Issues in GitHub if you have further requests :)
